/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type AuditActionType = { 'changeCodeStatus' : null } |
  { 'rotateCode' : null } |
  { 'viewCode' : null } |
  { 'updateCodeData' : null } |
  { 'copyCode' : null } |
  { 'generateNewCode' : null } |
  { 'toggleCodeVisibility' : null };
export interface AuditLogEntry {
  'metadata' : string,
  'actionType' : AuditActionType,
  'timestamp' : bigint,
  'principalId' : string,
}
export type AuditLogEntryList = Array<AuditLogEntry>;
export interface ClientRegistrationData {
  'name' : string,
  'whatsapp' : string,
  'email' : string,
  'company' : string,
}
export interface InternalAccessCode {
  'code' : string,
  'lastUpdated' : bigint,
  'codeType' : InternalCodeType,
}
export type InternalCodeType = { 'codeA' : null } |
  { 'codeB' : null };
export type InternalLoginType = { 'login' : null } |
  { 'register' : null };
export interface InternalRegistrationData {
  'name' : string,
  'whatsapp' : string,
  'email' : string,
}
export interface InternalUserDTO {
  'id' : string,
  'status' : UserStatus,
  'name' : string,
  'role' : string,
  'principalId' : string,
}
export type PartnerLevel = { 'level1' : null } |
  { 'level2' : null } |
  { 'level3' : null } |
  { 'level4' : null } |
  { 'level5' : null };
export interface PartnerRegistrationData {
  'name' : string,
  'hourlyRate' : bigint,
  'whatsapp' : string,
  'email' : string,
  'level' : PartnerLevel,
  'domisili' : string,
  'skills' : string,
}
export interface PartnerTaskDTO {
  'tasks' : Array<PartnerTaskRecord>,
  'partnerName' : string,
  'partnerId' : string,
}
export interface PartnerTaskRecord {
  'statusInternal' : TaskStatusInternal,
  'title' : string,
  'clientId' : string,
  'internalDeadline' : [] | [bigint],
  'assignedPartnerId' : [] | [string],
  'createdAt' : bigint,
  'description' : string,
  'assignedAsistenmuName' : string,
  'updatedAt' : bigint,
  'taskId' : string,
  'createdByPrincipal' : Principal,
  'requestType' : RequestType,
  'clientDeadline' : [] | [bigint],
}
export type PaymentStatus = { 'pending' : null } |
  { 'overpaid' : null } |
  { 'paid' : null } |
  { 'refunded' : null } |
  { 'unpaid' : null } |
  { 'partial' : null };
export type RequestType = { 'PRIORITY' : null } |
  { 'URGENT' : null } |
  { 'NORMAL' : null };
export interface Schedule {
  'startTime' : [] | [string],
  'allowsOvertime' : boolean,
  'endDate' : [] | [string],
  'endTime' : [] | [string],
  'additionalComments' : [] | [string],
  'timezoneOffset' : [] | [bigint],
  'includesWeekend' : boolean,
  'isRemote' : boolean,
  'startDate' : [] | [string],
}
export type SearchMode = { 'searchByClientId' : null } |
  { 'searchByClientPrincipal' : null } |
  { 'searchAll' : null };
export interface SearchResult {
  'users' : Array<UserProfile>,
  'services' : Array<Service>,
}
export interface Service {
  'id' : string,
  'additionalCost' : bigint,
  'status' : Status,
  'title' : string,
  'serviceQuantity' : bigint,
  'serviceType' : string,
  'thumbnail' : string,
  'code' : string,
  'icon' : string,
  'createdAt' : bigint,
  'unit' : string,
  'banner' : string,
  'description' : string,
  'available' : boolean,
  'updatedAt' : bigint,
  'estimatedTotal' : bigint,
  'maxDiscountPercent' : bigint,
  'category' : string,
  'estimatedTeamSize' : bigint,
  'price' : bigint,
  'estimatedTime' : string,
  'detailedInformation' : string,
}
export interface ServicePublic {
  'id' : string,
  'status' : Status,
  'title' : string,
  'serviceQuantity' : bigint,
  'serviceType' : string,
  'thumbnail' : string,
  'code' : string,
  'icon' : string,
  'createdAt' : bigint,
  'unit' : string,
  'banner' : string,
  'description' : string,
  'available' : boolean,
  'updatedAt' : bigint,
  'category' : string,
  'estimatedTeamSize' : bigint,
  'estimatedTime' : string,
  'detailedInformation' : string,
}
export type Status = { 'outdated' : null } |
  { 'review' : null } |
  { 'active' : null } |
  { 'pending' : null } |
  { 'inactive' : null } |
  { 'delisted' : null } |
  { 'archived' : null };
export interface Task {
  'id' : string,
  'title' : string,
  'paymentStatus' : PaymentStatus,
  'partnerTeamLeader' : string,
  'continuityFlag' : boolean,
  'clientSpecificRequirements' : string,
  'tags' : string,
  'extendedServiceDescription' : string,
  'taskStatus' : TaskStatus,
  'description' : string,
  'taskType' : string,
  'memberSlots' : bigint,
  'collaborativeFlag' : boolean,
  'internalProjectManager' : string,
  'prioritizedFlags' : string,
  'clientReferenceId' : string,
  'prioritizationScore' : bigint,
  'partnerTeamMembers' : Array<string>,
  'additionalServiceCost' : bigint,
  'overallTaskScore' : bigint,
  'onboardingMaterial' : string,
  'subtaskRequiredCount' : bigint,
  'serviceReference' : string,
  'schedule' : Schedule,
}
export interface TaskRecord {
  'statusInternal' : TaskStatusInternal,
  'title' : string,
  'clientId' : string,
  'internalDeadline' : [] | [bigint],
  'assignedPartnerId' : [] | [string],
  'createdAt' : bigint,
  'description' : string,
  'assignedAsistenmuName' : string,
  'updatedAt' : bigint,
  'taskId' : string,
  'createdByPrincipal' : Principal,
  'requestType' : RequestType,
  'clientDeadline' : [] | [bigint],
}
export type TaskStatus = { 'canceled' : null } |
  { 'open' : null } |
  { 'completed' : null } |
  { 'pendingForReview' : null } |
  { 'revising' : null } |
  { 'inProgress' : null };
export type TaskStatusInternal = { 'REQUESTED' : null } |
  { 'REVISION' : null } |
  { 'DONE' : null } |
  { 'IN_PROGRESS' : null } |
  { 'QA_ASISTENMU' : null };
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile {
  'id' : string,
  'status' : UserStatus,
  'partnerData' : [] | [PartnerRegistrationData],
  'clientData' : [] | [ClientRegistrationData],
  'internalData' : [] | [InternalRegistrationData],
  'role' : string,
  'principalId' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type UserStatus = { 'active' : null } |
  { 'pending' : null } |
  { 'suspended' : null } |
  { 'blacklisted' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'activateService' : ActorMethod<[string], boolean>,
  'approvePartner' : ActorMethod<[string], undefined>,
  'approvePartnerProposal' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignTaskToPartner' : ActorMethod<[string, string], boolean>,
  'blacklistPartner' : ActorMethod<[string], undefined>,
  'claimSuperadmin' : ActorMethod<[], string>,
  'createNewPartnerProposal' : ActorMethod<[PartnerRegistrationData], string>,
  'createService' : ActorMethod<[Service], undefined>,
  'createTaskLegacy' : ActorMethod<[Task], undefined>,
  'deactivateService' : ActorMethod<[string], boolean>,
  'generateRandomAccessCode' : ActorMethod<[InternalCodeType, string], string>,
  'getAccessCodes' : ActorMethod<[], Array<InternalAccessCode>>,
  'getActiveClientProfiles' : ActorMethod<[], Array<UserProfile>>,
  'getAllAuditLogsSorted' : ActorMethod<[string], AuditLogEntryList>,
  'getAllInternalUsers' : ActorMethod<[], Array<InternalUserDTO>>,
  'getAllPartnersByStatus' : ActorMethod<[UserStatus], Array<UserProfile>>,
  'getAllServices' : ActorMethod<[], Array<Service>>,
  'getAllServicesPublic' : ActorMethod<[], Array<ServicePublic>>,
  'getAllTasksInternal' : ActorMethod<[], Array<TaskRecord>>,
  'getAllTasksLegacy' : ActorMethod<[], Array<Task>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDefaultPartnerProfile' : ActorMethod<[], UserProfile>,
  'getMyPartnerTasks' : ActorMethod<[], PartnerTaskDTO>,
  'getServiceById' : ActorMethod<[string], [] | [Service]>,
  'getServiceByIdPublic' : ActorMethod<[string], [] | [ServicePublic]>,
  'getTaskById' : ActorMethod<[string], [] | [TaskRecord]>,
  'getTaskLegacy' : ActorMethod<[string], [] | [Task]>,
  'getUserProfile' : ActorMethod<[string], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'isSuperadminClaimed' : ActorMethod<[], boolean>,
  'isValidRoleName' : ActorMethod<[string], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'logAuditEntry' : ActorMethod<[AuditActionType, string], undefined>,
  'manageAccessCode' : ActorMethod<[InternalCodeType, string], undefined>,
  'reactivatePartner' : ActorMethod<[string], undefined>,
  'registerClient' : ActorMethod<[string, string, string, string], string>,
  'registerInternalUser' : ActorMethod<
    [string, string, string, string],
    string
  >,
  'registerPartner' : ActorMethod<
    [string, string, string, string, string, PartnerLevel, bigint],
    string
  >,
  'rejectPartner' : ActorMethod<[string], undefined>,
  'rejectPartnerProposal' : ActorMethod<[string], undefined>,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchServicesAndClientsById' : ActorMethod<
    [string, SearchMode],
    SearchResult
  >,
  'searchUsersByMode' : ActorMethod<[string, SearchMode], Array<UserProfile>>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'setTaskStatus' : ActorMethod<[string, TaskStatusInternal], boolean>,
  'suspendPartner' : ActorMethod<[string], undefined>,
  'updatePartnerLevelAndHourlyRate' : ActorMethod<
    [string, PartnerLevel, bigint],
    undefined
  >,
  'updateUserRole' : ActorMethod<[string, string], undefined>,
  'verifyAccessCode' : ActorMethod<[string], [] | [InternalLoginType]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];