/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ClientRegistrationData {
  'name' : string,
  'whatsapp' : string,
  'email' : string,
  'company' : string,
}
export interface FinancialPartnerData {
  'id' : string,
  'status' : [] | [string],
  'balance' : bigint,
  'partnerName' : string,
  'availableBalance' : bigint,
  'nbUpdate' : [] | [string],
  'pendingWithdrawals' : bigint,
  'createdAt' : [] | [string],
  'history' : Array<string>,
  'partnerId' : string,
  'insured' : bigint,
  'bonus' : bigint,
  'totalEarnings' : bigint,
  'withdrawn' : bigint,
}
export interface FinancialSummary {
  'completedPayouts' : bigint,
  'totalPayoutAmount' : bigint,
  'completedTransactions' : bigint,
  'totalTransactionAmount' : bigint,
}
export interface InternalRegistrationData {
  'name' : string,
  'whatsapp' : string,
  'email' : string,
}
export interface PartnerRegistrationData {
  'name' : string,
  'whatsapp' : string,
  'email' : string,
  'domisili' : string,
  'skills' : string,
}
export type PaymentStatus = { 'pending' : null } |
  { 'overpaid' : null } |
  { 'paid' : null } |
  { 'refunded' : null } |
  { 'unpaid' : null } |
  { 'partial' : null };
export interface Schedule {
  'startTime' : [] | [string],
  'allowsOvertime' : boolean,
  'endDate' : [] | [string],
  'endTime' : [] | [string],
  'additionalComments' : [] | [string],
  'timezoneOffset' : [] | [bigint],
  'includesWeekend' : boolean,
  'isRemote' : boolean,
  'startDate' : [] | [string],
}
export interface Service {
  'id' : string,
  'additionalCost' : bigint,
  'status' : Status,
  'title' : string,
  'serviceType' : string,
  'thumbnail' : string,
  'code' : string,
  'icon' : string,
  'createdAt' : bigint,
  'unit' : string,
  'banner' : string,
  'description' : string,
  'available' : boolean,
  'updatedAt' : bigint,
  'estimatedTotal' : bigint,
  'maxDiscountPercent' : bigint,
  'category' : string,
  'estimatedTeamSize' : bigint,
  'price' : bigint,
  'estimatedTime' : string,
  'detailedInformation' : string,
}
export type Status = { 'outdated' : null } |
  { 'review' : null } |
  { 'active' : null } |
  { 'pending' : null } |
  { 'inactive' : null } |
  { 'delisted' : null } |
  { 'archived' : null };
export interface Task {
  'id' : string,
  'title' : string,
  'paymentStatus' : PaymentStatus,
  'partnerTeamLeader' : string,
  'continuityFlag' : boolean,
  'clientSpecificRequirements' : string,
  'tags' : string,
  'extendedServiceDescription' : string,
  'taskStatus' : TaskStatus,
  'description' : string,
  'taskType' : string,
  'memberSlots' : bigint,
  'collaborativeFlag' : boolean,
  'internalProjectManager' : string,
  'prioritizedFlags' : string,
  'clientReferenceId' : string,
  'prioritizationScore' : bigint,
  'partnerTeamMembers' : Array<string>,
  'additionalServiceCost' : bigint,
  'overallTaskScore' : bigint,
  'onboardingMaterial' : string,
  'subtaskRequiredCount' : bigint,
  'serviceReference' : string,
  'schedule' : Schedule,
}
export type TaskStatus = { 'canceled' : null } |
  { 'open' : null } |
  { 'completed' : null } |
  { 'pendingForReview' : null } |
  { 'revising' : null } |
  { 'inProgress' : null };
export interface UserProfile {
  'id' : string,
  'status' : UserStatus,
  'partnerData' : [] | [PartnerRegistrationData],
  'clientData' : [] | [ClientRegistrationData],
  'internalData' : [] | [InternalRegistrationData],
  'role' : string,
  'principalId' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type UserStatus = { 'active' : null } |
  { 'pending' : null } |
  { 'suspended' : null } |
  { 'blacklisted' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'claimSuperadmin' : ActorMethod<[], string>,
  'createFinancialPartnerData' : ActorMethod<[FinancialPartnerData], undefined>,
  'createService' : ActorMethod<[Service], undefined>,
  'createTask' : ActorMethod<[Task], undefined>,
  'getAllFinancialPartnerData' : ActorMethod<[], Array<FinancialPartnerData>>,
  'getAllServices' : ActorMethod<[], Array<Service>>,
  'getAllTasks' : ActorMethod<[], Array<Task>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDefaultPartnerProfile' : ActorMethod<[], UserProfile>,
  'getFinancialPartnerDataById' : ActorMethod<
    [string],
    [] | [FinancialPartnerData]
  >,
  'getFinancialSummary' : ActorMethod<[], FinancialSummary>,
  'getMyWallet' : ActorMethod<[], FinancialPartnerData>,
  'getServiceById' : ActorMethod<[string], [] | [Service]>,
  'getTaskById' : ActorMethod<[string], [] | [Task]>,
  'getUserProfile' : ActorMethod<[string], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isValidRoleName' : ActorMethod<[string], boolean>,
  'registerClient' : ActorMethod<[string, string, string, string], string>,
  'registerInternalUser' : ActorMethod<
    [string, string, string, string],
    string
  >,
  'registerPartner' : ActorMethod<
    [string, string, string, string, string],
    string
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];