/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PartnerLevel = IDL.Variant({
  'level1' : IDL.Null,
  'level2' : IDL.Null,
  'level3' : IDL.Null,
  'level4' : IDL.Null,
  'level5' : IDL.Null,
});
export const PartnerRegistrationData = IDL.Record({
  'name' : IDL.Text,
  'hourlyRate' : IDL.Nat,
  'whatsapp' : IDL.Text,
  'email' : IDL.Text,
  'level' : PartnerLevel,
  'domisili' : IDL.Text,
  'skills' : IDL.Text,
});
export const Status = IDL.Variant({
  'outdated' : IDL.Null,
  'review' : IDL.Null,
  'active' : IDL.Null,
  'pending' : IDL.Null,
  'inactive' : IDL.Null,
  'delisted' : IDL.Null,
  'archived' : IDL.Null,
});
export const Service = IDL.Record({
  'id' : IDL.Text,
  'additionalCost' : IDL.Nat,
  'status' : Status,
  'title' : IDL.Text,
  'serviceQuantity' : IDL.Nat,
  'serviceType' : IDL.Text,
  'thumbnail' : IDL.Text,
  'code' : IDL.Text,
  'icon' : IDL.Text,
  'createdAt' : IDL.Nat,
  'unit' : IDL.Text,
  'banner' : IDL.Text,
  'description' : IDL.Text,
  'available' : IDL.Bool,
  'updatedAt' : IDL.Nat,
  'estimatedTotal' : IDL.Nat,
  'maxDiscountPercent' : IDL.Nat,
  'category' : IDL.Text,
  'estimatedTeamSize' : IDL.Nat,
  'price' : IDL.Nat,
  'estimatedTime' : IDL.Text,
  'detailedInformation' : IDL.Text,
});
export const PaymentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'overpaid' : IDL.Null,
  'paid' : IDL.Null,
  'refunded' : IDL.Null,
  'unpaid' : IDL.Null,
  'partial' : IDL.Null,
});
export const TaskStatus = IDL.Variant({
  'canceled' : IDL.Null,
  'open' : IDL.Null,
  'completed' : IDL.Null,
  'pendingForReview' : IDL.Null,
  'revising' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Schedule = IDL.Record({
  'startTime' : IDL.Opt(IDL.Text),
  'allowsOvertime' : IDL.Bool,
  'endDate' : IDL.Opt(IDL.Text),
  'endTime' : IDL.Opt(IDL.Text),
  'additionalComments' : IDL.Opt(IDL.Text),
  'timezoneOffset' : IDL.Opt(IDL.Int),
  'includesWeekend' : IDL.Bool,
  'isRemote' : IDL.Bool,
  'startDate' : IDL.Opt(IDL.Text),
});
export const Task = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'paymentStatus' : PaymentStatus,
  'partnerTeamLeader' : IDL.Text,
  'continuityFlag' : IDL.Bool,
  'clientSpecificRequirements' : IDL.Text,
  'tags' : IDL.Text,
  'extendedServiceDescription' : IDL.Text,
  'taskStatus' : TaskStatus,
  'description' : IDL.Text,
  'taskType' : IDL.Text,
  'memberSlots' : IDL.Nat,
  'collaborativeFlag' : IDL.Bool,
  'internalProjectManager' : IDL.Text,
  'prioritizedFlags' : IDL.Text,
  'clientReferenceId' : IDL.Text,
  'prioritizationScore' : IDL.Nat,
  'partnerTeamMembers' : IDL.Vec(IDL.Text),
  'additionalServiceCost' : IDL.Nat,
  'overallTaskScore' : IDL.Nat,
  'onboardingMaterial' : IDL.Text,
  'subtaskRequiredCount' : IDL.Nat,
  'serviceReference' : IDL.Text,
  'schedule' : Schedule,
});
export const InternalCodeType = IDL.Variant({
  'codeA' : IDL.Null,
  'codeB' : IDL.Null,
});
export const InternalAccessCode = IDL.Record({
  'code' : IDL.Text,
  'lastUpdated' : IDL.Nat,
  'codeType' : InternalCodeType,
});
export const UserStatus = IDL.Variant({
  'active' : IDL.Null,
  'pending' : IDL.Null,
  'suspended' : IDL.Null,
  'blacklisted' : IDL.Null,
});
export const ClientRegistrationData = IDL.Record({
  'name' : IDL.Text,
  'whatsapp' : IDL.Text,
  'email' : IDL.Text,
  'company' : IDL.Text,
});
export const InternalRegistrationData = IDL.Record({
  'name' : IDL.Text,
  'whatsapp' : IDL.Text,
  'email' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'id' : IDL.Text,
  'status' : UserStatus,
  'partnerData' : IDL.Opt(PartnerRegistrationData),
  'clientData' : IDL.Opt(ClientRegistrationData),
  'internalData' : IDL.Opt(InternalRegistrationData),
  'role' : IDL.Text,
  'principalId' : IDL.Text,
});
export const AuditActionType = IDL.Variant({
  'changeCodeStatus' : IDL.Null,
  'rotateCode' : IDL.Null,
  'viewCode' : IDL.Null,
  'updateCodeData' : IDL.Null,
  'copyCode' : IDL.Null,
  'generateNewCode' : IDL.Null,
  'toggleCodeVisibility' : IDL.Null,
});
export const AuditLogEntry = IDL.Record({
  'metadata' : IDL.Text,
  'actionType' : AuditActionType,
  'timestamp' : IDL.Nat,
  'principalId' : IDL.Text,
});
export const AuditLogEntryList = IDL.Vec(AuditLogEntry);
export const InternalUserDTO = IDL.Record({
  'id' : IDL.Text,
  'status' : UserStatus,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'principalId' : IDL.Text,
});
export const ServicePublic = IDL.Record({
  'id' : IDL.Text,
  'status' : Status,
  'title' : IDL.Text,
  'serviceQuantity' : IDL.Nat,
  'serviceType' : IDL.Text,
  'thumbnail' : IDL.Text,
  'code' : IDL.Text,
  'icon' : IDL.Text,
  'createdAt' : IDL.Nat,
  'unit' : IDL.Text,
  'banner' : IDL.Text,
  'description' : IDL.Text,
  'available' : IDL.Bool,
  'updatedAt' : IDL.Nat,
  'category' : IDL.Text,
  'estimatedTeamSize' : IDL.Nat,
  'estimatedTime' : IDL.Text,
  'detailedInformation' : IDL.Text,
});
export const TaskStatusInternal = IDL.Variant({
  'REQUESTED' : IDL.Null,
  'REVISION' : IDL.Null,
  'DONE' : IDL.Null,
  'IN_PROGRESS' : IDL.Null,
  'QA_ASISTENMU' : IDL.Null,
});
export const RequestType = IDL.Variant({
  'PRIORITY' : IDL.Null,
  'URGENT' : IDL.Null,
  'NORMAL' : IDL.Null,
});
export const TaskRecord = IDL.Record({
  'statusInternal' : TaskStatusInternal,
  'title' : IDL.Text,
  'clientId' : IDL.Text,
  'internalDeadline' : IDL.Opt(IDL.Nat),
  'assignedPartnerId' : IDL.Opt(IDL.Text),
  'createdAt' : IDL.Nat,
  'description' : IDL.Text,
  'assignedAsistenmuName' : IDL.Text,
  'updatedAt' : IDL.Nat,
  'taskId' : IDL.Text,
  'createdByPrincipal' : IDL.Principal,
  'requestType' : RequestType,
  'clientDeadline' : IDL.Opt(IDL.Nat),
});
export const PartnerTaskRecord = IDL.Record({
  'statusInternal' : TaskStatusInternal,
  'title' : IDL.Text,
  'clientId' : IDL.Text,
  'internalDeadline' : IDL.Opt(IDL.Nat),
  'assignedPartnerId' : IDL.Opt(IDL.Text),
  'createdAt' : IDL.Nat,
  'description' : IDL.Text,
  'assignedAsistenmuName' : IDL.Text,
  'updatedAt' : IDL.Nat,
  'taskId' : IDL.Text,
  'createdByPrincipal' : IDL.Principal,
  'requestType' : RequestType,
  'clientDeadline' : IDL.Opt(IDL.Nat),
});
export const PartnerTaskDTO = IDL.Record({
  'tasks' : IDL.Vec(PartnerTaskRecord),
  'partnerName' : IDL.Text,
  'partnerId' : IDL.Text,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});
export const SearchMode = IDL.Variant({
  'searchByClientId' : IDL.Null,
  'searchByClientPrincipal' : IDL.Null,
  'searchAll' : IDL.Null,
});
export const SearchResult = IDL.Record({
  'users' : IDL.Vec(UserProfile),
  'services' : IDL.Vec(Service),
});
export const InternalLoginType = IDL.Variant({
  'login' : IDL.Null,
  'register' : IDL.Null,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'activateService' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'approvePartner' : IDL.Func([IDL.Text], [], []),
  'approvePartnerProposal' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignTaskToPartner' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'blacklistPartner' : IDL.Func([IDL.Text], [], []),
  'claimSuperadmin' : IDL.Func([], [IDL.Text], []),
  'createNewPartnerProposal' : IDL.Func(
      [PartnerRegistrationData],
      [IDL.Text],
      [],
    ),
  'createService' : IDL.Func([Service], [], []),
  'createTaskLegacy' : IDL.Func([Task], [], []),
  'deactivateService' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'generateRandomAccessCode' : IDL.Func(
      [InternalCodeType, IDL.Text],
      [IDL.Text],
      [],
    ),
  'getAccessCodes' : IDL.Func([], [IDL.Vec(InternalAccessCode)], ['query']),
  'getActiveClientProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getAllAuditLogsSorted' : IDL.Func(
      [IDL.Text],
      [AuditLogEntryList],
      ['query'],
    ),
  'getAllInternalUsers' : IDL.Func([], [IDL.Vec(InternalUserDTO)], ['query']),
  'getAllPartnersByStatus' : IDL.Func(
      [UserStatus],
      [IDL.Vec(UserProfile)],
      ['query'],
    ),
  'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getAllServicesPublic' : IDL.Func([], [IDL.Vec(ServicePublic)], ['query']),
  'getAllTasksInternal' : IDL.Func([], [IDL.Vec(TaskRecord)], ['query']),
  'getAllTasksLegacy' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDefaultPartnerProfile' : IDL.Func([], [UserProfile], ['query']),
  'getMyPartnerTasks' : IDL.Func([], [PartnerTaskDTO], ['query']),
  'getServiceById' : IDL.Func([IDL.Text], [IDL.Opt(Service)], ['query']),
  'getServiceByIdPublic' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(ServicePublic)],
      ['query'],
    ),
  'getTaskById' : IDL.Func([IDL.Text], [IDL.Opt(TaskRecord)], ['query']),
  'getTaskLegacy' : IDL.Func([IDL.Text], [IDL.Opt(Task)], ['query']),
  'getUserProfile' : IDL.Func([IDL.Text], [IDL.Opt(UserProfile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'isValidRoleName' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'logAuditEntry' : IDL.Func([AuditActionType, IDL.Text], [], []),
  'manageAccessCode' : IDL.Func([InternalCodeType, IDL.Text], [], []),
  'reactivatePartner' : IDL.Func([IDL.Text], [], []),
  'registerClient' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'registerInternalUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'registerPartner' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, PartnerLevel, IDL.Nat],
      [IDL.Text],
      [],
    ),
  'rejectPartner' : IDL.Func([IDL.Text], [], []),
  'rejectPartnerProposal' : IDL.Func([IDL.Text], [], []),
  'requestApproval' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchServicesAndClientsById' : IDL.Func(
      [IDL.Text, SearchMode],
      [SearchResult],
      ['query'],
    ),
  'searchUsersByMode' : IDL.Func(
      [IDL.Text, SearchMode],
      [IDL.Vec(UserProfile)],
      ['query'],
    ),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'setTaskStatus' : IDL.Func([IDL.Text, TaskStatusInternal], [IDL.Bool], []),
  'suspendPartner' : IDL.Func([IDL.Text], [], []),
  'updatePartnerLevelAndHourlyRate' : IDL.Func(
      [IDL.Text, PartnerLevel, IDL.Nat],
      [],
      [],
    ),
  'updateUserRole' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'verifyAccessCode' : IDL.Func([IDL.Text], [IDL.Opt(InternalLoginType)], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PartnerLevel = IDL.Variant({
    'level1' : IDL.Null,
    'level2' : IDL.Null,
    'level3' : IDL.Null,
    'level4' : IDL.Null,
    'level5' : IDL.Null,
  });
  const PartnerRegistrationData = IDL.Record({
    'name' : IDL.Text,
    'hourlyRate' : IDL.Nat,
    'whatsapp' : IDL.Text,
    'email' : IDL.Text,
    'level' : PartnerLevel,
    'domisili' : IDL.Text,
    'skills' : IDL.Text,
  });
  const Status = IDL.Variant({
    'outdated' : IDL.Null,
    'review' : IDL.Null,
    'active' : IDL.Null,
    'pending' : IDL.Null,
    'inactive' : IDL.Null,
    'delisted' : IDL.Null,
    'archived' : IDL.Null,
  });
  const Service = IDL.Record({
    'id' : IDL.Text,
    'additionalCost' : IDL.Nat,
    'status' : Status,
    'title' : IDL.Text,
    'serviceQuantity' : IDL.Nat,
    'serviceType' : IDL.Text,
    'thumbnail' : IDL.Text,
    'code' : IDL.Text,
    'icon' : IDL.Text,
    'createdAt' : IDL.Nat,
    'unit' : IDL.Text,
    'banner' : IDL.Text,
    'description' : IDL.Text,
    'available' : IDL.Bool,
    'updatedAt' : IDL.Nat,
    'estimatedTotal' : IDL.Nat,
    'maxDiscountPercent' : IDL.Nat,
    'category' : IDL.Text,
    'estimatedTeamSize' : IDL.Nat,
    'price' : IDL.Nat,
    'estimatedTime' : IDL.Text,
    'detailedInformation' : IDL.Text,
  });
  const PaymentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'overpaid' : IDL.Null,
    'paid' : IDL.Null,
    'refunded' : IDL.Null,
    'unpaid' : IDL.Null,
    'partial' : IDL.Null,
  });
  const TaskStatus = IDL.Variant({
    'canceled' : IDL.Null,
    'open' : IDL.Null,
    'completed' : IDL.Null,
    'pendingForReview' : IDL.Null,
    'revising' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Schedule = IDL.Record({
    'startTime' : IDL.Opt(IDL.Text),
    'allowsOvertime' : IDL.Bool,
    'endDate' : IDL.Opt(IDL.Text),
    'endTime' : IDL.Opt(IDL.Text),
    'additionalComments' : IDL.Opt(IDL.Text),
    'timezoneOffset' : IDL.Opt(IDL.Int),
    'includesWeekend' : IDL.Bool,
    'isRemote' : IDL.Bool,
    'startDate' : IDL.Opt(IDL.Text),
  });
  const Task = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'paymentStatus' : PaymentStatus,
    'partnerTeamLeader' : IDL.Text,
    'continuityFlag' : IDL.Bool,
    'clientSpecificRequirements' : IDL.Text,
    'tags' : IDL.Text,
    'extendedServiceDescription' : IDL.Text,
    'taskStatus' : TaskStatus,
    'description' : IDL.Text,
    'taskType' : IDL.Text,
    'memberSlots' : IDL.Nat,
    'collaborativeFlag' : IDL.Bool,
    'internalProjectManager' : IDL.Text,
    'prioritizedFlags' : IDL.Text,
    'clientReferenceId' : IDL.Text,
    'prioritizationScore' : IDL.Nat,
    'partnerTeamMembers' : IDL.Vec(IDL.Text),
    'additionalServiceCost' : IDL.Nat,
    'overallTaskScore' : IDL.Nat,
    'onboardingMaterial' : IDL.Text,
    'subtaskRequiredCount' : IDL.Nat,
    'serviceReference' : IDL.Text,
    'schedule' : Schedule,
  });
  const InternalCodeType = IDL.Variant({
    'codeA' : IDL.Null,
    'codeB' : IDL.Null,
  });
  const InternalAccessCode = IDL.Record({
    'code' : IDL.Text,
    'lastUpdated' : IDL.Nat,
    'codeType' : InternalCodeType,
  });
  const UserStatus = IDL.Variant({
    'active' : IDL.Null,
    'pending' : IDL.Null,
    'suspended' : IDL.Null,
    'blacklisted' : IDL.Null,
  });
  const ClientRegistrationData = IDL.Record({
    'name' : IDL.Text,
    'whatsapp' : IDL.Text,
    'email' : IDL.Text,
    'company' : IDL.Text,
  });
  const InternalRegistrationData = IDL.Record({
    'name' : IDL.Text,
    'whatsapp' : IDL.Text,
    'email' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'id' : IDL.Text,
    'status' : UserStatus,
    'partnerData' : IDL.Opt(PartnerRegistrationData),
    'clientData' : IDL.Opt(ClientRegistrationData),
    'internalData' : IDL.Opt(InternalRegistrationData),
    'role' : IDL.Text,
    'principalId' : IDL.Text,
  });
  const AuditActionType = IDL.Variant({
    'changeCodeStatus' : IDL.Null,
    'rotateCode' : IDL.Null,
    'viewCode' : IDL.Null,
    'updateCodeData' : IDL.Null,
    'copyCode' : IDL.Null,
    'generateNewCode' : IDL.Null,
    'toggleCodeVisibility' : IDL.Null,
  });
  const AuditLogEntry = IDL.Record({
    'metadata' : IDL.Text,
    'actionType' : AuditActionType,
    'timestamp' : IDL.Nat,
    'principalId' : IDL.Text,
  });
  const AuditLogEntryList = IDL.Vec(AuditLogEntry);
  const InternalUserDTO = IDL.Record({
    'id' : IDL.Text,
    'status' : UserStatus,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'principalId' : IDL.Text,
  });
  const ServicePublic = IDL.Record({
    'id' : IDL.Text,
    'status' : Status,
    'title' : IDL.Text,
    'serviceQuantity' : IDL.Nat,
    'serviceType' : IDL.Text,
    'thumbnail' : IDL.Text,
    'code' : IDL.Text,
    'icon' : IDL.Text,
    'createdAt' : IDL.Nat,
    'unit' : IDL.Text,
    'banner' : IDL.Text,
    'description' : IDL.Text,
    'available' : IDL.Bool,
    'updatedAt' : IDL.Nat,
    'category' : IDL.Text,
    'estimatedTeamSize' : IDL.Nat,
    'estimatedTime' : IDL.Text,
    'detailedInformation' : IDL.Text,
  });
  const TaskStatusInternal = IDL.Variant({
    'REQUESTED' : IDL.Null,
    'REVISION' : IDL.Null,
    'DONE' : IDL.Null,
    'IN_PROGRESS' : IDL.Null,
    'QA_ASISTENMU' : IDL.Null,
  });
  const RequestType = IDL.Variant({
    'PRIORITY' : IDL.Null,
    'URGENT' : IDL.Null,
    'NORMAL' : IDL.Null,
  });
  const TaskRecord = IDL.Record({
    'statusInternal' : TaskStatusInternal,
    'title' : IDL.Text,
    'clientId' : IDL.Text,
    'internalDeadline' : IDL.Opt(IDL.Nat),
    'assignedPartnerId' : IDL.Opt(IDL.Text),
    'createdAt' : IDL.Nat,
    'description' : IDL.Text,
    'assignedAsistenmuName' : IDL.Text,
    'updatedAt' : IDL.Nat,
    'taskId' : IDL.Text,
    'createdByPrincipal' : IDL.Principal,
    'requestType' : RequestType,
    'clientDeadline' : IDL.Opt(IDL.Nat),
  });
  const PartnerTaskRecord = IDL.Record({
    'statusInternal' : TaskStatusInternal,
    'title' : IDL.Text,
    'clientId' : IDL.Text,
    'internalDeadline' : IDL.Opt(IDL.Nat),
    'assignedPartnerId' : IDL.Opt(IDL.Text),
    'createdAt' : IDL.Nat,
    'description' : IDL.Text,
    'assignedAsistenmuName' : IDL.Text,
    'updatedAt' : IDL.Nat,
    'taskId' : IDL.Text,
    'createdByPrincipal' : IDL.Principal,
    'requestType' : RequestType,
    'clientDeadline' : IDL.Opt(IDL.Nat),
  });
  const PartnerTaskDTO = IDL.Record({
    'tasks' : IDL.Vec(PartnerTaskRecord),
    'partnerName' : IDL.Text,
    'partnerId' : IDL.Text,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  const SearchMode = IDL.Variant({
    'searchByClientId' : IDL.Null,
    'searchByClientPrincipal' : IDL.Null,
    'searchAll' : IDL.Null,
  });
  const SearchResult = IDL.Record({
    'users' : IDL.Vec(UserProfile),
    'services' : IDL.Vec(Service),
  });
  const InternalLoginType = IDL.Variant({
    'login' : IDL.Null,
    'register' : IDL.Null,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'activateService' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'approvePartner' : IDL.Func([IDL.Text], [], []),
    'approvePartnerProposal' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignTaskToPartner' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'blacklistPartner' : IDL.Func([IDL.Text], [], []),
    'claimSuperadmin' : IDL.Func([], [IDL.Text], []),
    'createNewPartnerProposal' : IDL.Func(
        [PartnerRegistrationData],
        [IDL.Text],
        [],
      ),
    'createService' : IDL.Func([Service], [], []),
    'createTaskLegacy' : IDL.Func([Task], [], []),
    'deactivateService' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'generateRandomAccessCode' : IDL.Func(
        [InternalCodeType, IDL.Text],
        [IDL.Text],
        [],
      ),
    'getAccessCodes' : IDL.Func([], [IDL.Vec(InternalAccessCode)], ['query']),
    'getActiveClientProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getAllAuditLogsSorted' : IDL.Func(
        [IDL.Text],
        [AuditLogEntryList],
        ['query'],
      ),
    'getAllInternalUsers' : IDL.Func([], [IDL.Vec(InternalUserDTO)], ['query']),
    'getAllPartnersByStatus' : IDL.Func(
        [UserStatus],
        [IDL.Vec(UserProfile)],
        ['query'],
      ),
    'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getAllServicesPublic' : IDL.Func([], [IDL.Vec(ServicePublic)], ['query']),
    'getAllTasksInternal' : IDL.Func([], [IDL.Vec(TaskRecord)], ['query']),
    'getAllTasksLegacy' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDefaultPartnerProfile' : IDL.Func([], [UserProfile], ['query']),
    'getMyPartnerTasks' : IDL.Func([], [PartnerTaskDTO], ['query']),
    'getServiceById' : IDL.Func([IDL.Text], [IDL.Opt(Service)], ['query']),
    'getServiceByIdPublic' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ServicePublic)],
        ['query'],
      ),
    'getTaskById' : IDL.Func([IDL.Text], [IDL.Opt(TaskRecord)], ['query']),
    'getTaskLegacy' : IDL.Func([IDL.Text], [IDL.Opt(Task)], ['query']),
    'getUserProfile' : IDL.Func([IDL.Text], [IDL.Opt(UserProfile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'isValidRoleName' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'logAuditEntry' : IDL.Func([AuditActionType, IDL.Text], [], []),
    'manageAccessCode' : IDL.Func([InternalCodeType, IDL.Text], [], []),
    'reactivatePartner' : IDL.Func([IDL.Text], [], []),
    'registerClient' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'registerInternalUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'registerPartner' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          PartnerLevel,
          IDL.Nat,
        ],
        [IDL.Text],
        [],
      ),
    'rejectPartner' : IDL.Func([IDL.Text], [], []),
    'rejectPartnerProposal' : IDL.Func([IDL.Text], [], []),
    'requestApproval' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchServicesAndClientsById' : IDL.Func(
        [IDL.Text, SearchMode],
        [SearchResult],
        ['query'],
      ),
    'searchUsersByMode' : IDL.Func(
        [IDL.Text, SearchMode],
        [IDL.Vec(UserProfile)],
        ['query'],
      ),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'setTaskStatus' : IDL.Func([IDL.Text, TaskStatusInternal], [IDL.Bool], []),
    'suspendPartner' : IDL.Func([IDL.Text], [], []),
    'updatePartnerLevelAndHourlyRate' : IDL.Func(
        [IDL.Text, PartnerLevel, IDL.Nat],
        [],
        [],
      ),
    'updateUserRole' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'verifyAccessCode' : IDL.Func([IDL.Text], [IDL.Opt(InternalLoginType)], []),
  });
};

export const init = ({ IDL }) => { return []; };