/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const FinancialPartnerData = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Opt(IDL.Text),
  'balance' : IDL.Nat,
  'partnerName' : IDL.Text,
  'availableBalance' : IDL.Nat,
  'nbUpdate' : IDL.Opt(IDL.Text),
  'pendingWithdrawals' : IDL.Nat,
  'createdAt' : IDL.Opt(IDL.Text),
  'history' : IDL.Vec(IDL.Text),
  'partnerId' : IDL.Text,
  'insured' : IDL.Nat,
  'bonus' : IDL.Nat,
  'totalEarnings' : IDL.Nat,
  'withdrawn' : IDL.Nat,
});
export const Status = IDL.Variant({
  'outdated' : IDL.Null,
  'review' : IDL.Null,
  'active' : IDL.Null,
  'pending' : IDL.Null,
  'inactive' : IDL.Null,
  'delisted' : IDL.Null,
  'archived' : IDL.Null,
});
export const Service = IDL.Record({
  'id' : IDL.Text,
  'additionalCost' : IDL.Nat,
  'status' : Status,
  'title' : IDL.Text,
  'serviceType' : IDL.Text,
  'thumbnail' : IDL.Text,
  'code' : IDL.Text,
  'icon' : IDL.Text,
  'createdAt' : IDL.Nat,
  'unit' : IDL.Text,
  'banner' : IDL.Text,
  'description' : IDL.Text,
  'available' : IDL.Bool,
  'updatedAt' : IDL.Nat,
  'estimatedTotal' : IDL.Nat,
  'maxDiscountPercent' : IDL.Nat,
  'category' : IDL.Text,
  'estimatedTeamSize' : IDL.Nat,
  'price' : IDL.Nat,
  'estimatedTime' : IDL.Text,
  'detailedInformation' : IDL.Text,
});
export const PaymentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'overpaid' : IDL.Null,
  'paid' : IDL.Null,
  'refunded' : IDL.Null,
  'unpaid' : IDL.Null,
  'partial' : IDL.Null,
});
export const TaskStatus = IDL.Variant({
  'canceled' : IDL.Null,
  'open' : IDL.Null,
  'completed' : IDL.Null,
  'pendingForReview' : IDL.Null,
  'revising' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Schedule = IDL.Record({
  'startTime' : IDL.Opt(IDL.Text),
  'allowsOvertime' : IDL.Bool,
  'endDate' : IDL.Opt(IDL.Text),
  'endTime' : IDL.Opt(IDL.Text),
  'additionalComments' : IDL.Opt(IDL.Text),
  'timezoneOffset' : IDL.Opt(IDL.Int),
  'includesWeekend' : IDL.Bool,
  'isRemote' : IDL.Bool,
  'startDate' : IDL.Opt(IDL.Text),
});
export const Task = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'paymentStatus' : PaymentStatus,
  'partnerTeamLeader' : IDL.Text,
  'continuityFlag' : IDL.Bool,
  'clientSpecificRequirements' : IDL.Text,
  'tags' : IDL.Text,
  'extendedServiceDescription' : IDL.Text,
  'taskStatus' : TaskStatus,
  'description' : IDL.Text,
  'taskType' : IDL.Text,
  'memberSlots' : IDL.Nat,
  'collaborativeFlag' : IDL.Bool,
  'internalProjectManager' : IDL.Text,
  'prioritizedFlags' : IDL.Text,
  'clientReferenceId' : IDL.Text,
  'prioritizationScore' : IDL.Nat,
  'partnerTeamMembers' : IDL.Vec(IDL.Text),
  'additionalServiceCost' : IDL.Nat,
  'overallTaskScore' : IDL.Nat,
  'onboardingMaterial' : IDL.Text,
  'subtaskRequiredCount' : IDL.Nat,
  'serviceReference' : IDL.Text,
  'schedule' : Schedule,
});
export const UserStatus = IDL.Variant({
  'active' : IDL.Null,
  'pending' : IDL.Null,
  'suspended' : IDL.Null,
  'blacklisted' : IDL.Null,
});
export const PartnerRegistrationData = IDL.Record({
  'name' : IDL.Text,
  'whatsapp' : IDL.Text,
  'email' : IDL.Text,
  'domisili' : IDL.Text,
  'skills' : IDL.Text,
});
export const ClientRegistrationData = IDL.Record({
  'name' : IDL.Text,
  'whatsapp' : IDL.Text,
  'email' : IDL.Text,
  'company' : IDL.Text,
});
export const InternalRegistrationData = IDL.Record({
  'name' : IDL.Text,
  'whatsapp' : IDL.Text,
  'email' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'id' : IDL.Text,
  'status' : UserStatus,
  'partnerData' : IDL.Opt(PartnerRegistrationData),
  'clientData' : IDL.Opt(ClientRegistrationData),
  'internalData' : IDL.Opt(InternalRegistrationData),
  'role' : IDL.Text,
  'principalId' : IDL.Text,
});
export const FinancialSummary = IDL.Record({
  'completedPayouts' : IDL.Nat,
  'totalPayoutAmount' : IDL.Nat,
  'completedTransactions' : IDL.Nat,
  'totalTransactionAmount' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'claimSuperadmin' : IDL.Func([], [IDL.Text], []),
  'createFinancialPartnerData' : IDL.Func([FinancialPartnerData], [], []),
  'createService' : IDL.Func([Service], [], []),
  'createTask' : IDL.Func([Task], [], []),
  'getAllFinancialPartnerData' : IDL.Func(
      [],
      [IDL.Vec(FinancialPartnerData)],
      ['query'],
    ),
  'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDefaultPartnerProfile' : IDL.Func([], [UserProfile], ['query']),
  'getFinancialPartnerDataById' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(FinancialPartnerData)],
      ['query'],
    ),
  'getFinancialSummary' : IDL.Func([], [FinancialSummary], ['query']),
  'getMyWallet' : IDL.Func([], [FinancialPartnerData], ['query']),
  'getServiceById' : IDL.Func([IDL.Text], [IDL.Opt(Service)], ['query']),
  'getTaskById' : IDL.Func([IDL.Text], [IDL.Opt(Task)], ['query']),
  'getUserProfile' : IDL.Func([IDL.Text], [IDL.Opt(UserProfile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isValidRoleName' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'registerClient' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'registerInternalUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'registerPartner' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const FinancialPartnerData = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Opt(IDL.Text),
    'balance' : IDL.Nat,
    'partnerName' : IDL.Text,
    'availableBalance' : IDL.Nat,
    'nbUpdate' : IDL.Opt(IDL.Text),
    'pendingWithdrawals' : IDL.Nat,
    'createdAt' : IDL.Opt(IDL.Text),
    'history' : IDL.Vec(IDL.Text),
    'partnerId' : IDL.Text,
    'insured' : IDL.Nat,
    'bonus' : IDL.Nat,
    'totalEarnings' : IDL.Nat,
    'withdrawn' : IDL.Nat,
  });
  const Status = IDL.Variant({
    'outdated' : IDL.Null,
    'review' : IDL.Null,
    'active' : IDL.Null,
    'pending' : IDL.Null,
    'inactive' : IDL.Null,
    'delisted' : IDL.Null,
    'archived' : IDL.Null,
  });
  const Service = IDL.Record({
    'id' : IDL.Text,
    'additionalCost' : IDL.Nat,
    'status' : Status,
    'title' : IDL.Text,
    'serviceType' : IDL.Text,
    'thumbnail' : IDL.Text,
    'code' : IDL.Text,
    'icon' : IDL.Text,
    'createdAt' : IDL.Nat,
    'unit' : IDL.Text,
    'banner' : IDL.Text,
    'description' : IDL.Text,
    'available' : IDL.Bool,
    'updatedAt' : IDL.Nat,
    'estimatedTotal' : IDL.Nat,
    'maxDiscountPercent' : IDL.Nat,
    'category' : IDL.Text,
    'estimatedTeamSize' : IDL.Nat,
    'price' : IDL.Nat,
    'estimatedTime' : IDL.Text,
    'detailedInformation' : IDL.Text,
  });
  const PaymentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'overpaid' : IDL.Null,
    'paid' : IDL.Null,
    'refunded' : IDL.Null,
    'unpaid' : IDL.Null,
    'partial' : IDL.Null,
  });
  const TaskStatus = IDL.Variant({
    'canceled' : IDL.Null,
    'open' : IDL.Null,
    'completed' : IDL.Null,
    'pendingForReview' : IDL.Null,
    'revising' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Schedule = IDL.Record({
    'startTime' : IDL.Opt(IDL.Text),
    'allowsOvertime' : IDL.Bool,
    'endDate' : IDL.Opt(IDL.Text),
    'endTime' : IDL.Opt(IDL.Text),
    'additionalComments' : IDL.Opt(IDL.Text),
    'timezoneOffset' : IDL.Opt(IDL.Int),
    'includesWeekend' : IDL.Bool,
    'isRemote' : IDL.Bool,
    'startDate' : IDL.Opt(IDL.Text),
  });
  const Task = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'paymentStatus' : PaymentStatus,
    'partnerTeamLeader' : IDL.Text,
    'continuityFlag' : IDL.Bool,
    'clientSpecificRequirements' : IDL.Text,
    'tags' : IDL.Text,
    'extendedServiceDescription' : IDL.Text,
    'taskStatus' : TaskStatus,
    'description' : IDL.Text,
    'taskType' : IDL.Text,
    'memberSlots' : IDL.Nat,
    'collaborativeFlag' : IDL.Bool,
    'internalProjectManager' : IDL.Text,
    'prioritizedFlags' : IDL.Text,
    'clientReferenceId' : IDL.Text,
    'prioritizationScore' : IDL.Nat,
    'partnerTeamMembers' : IDL.Vec(IDL.Text),
    'additionalServiceCost' : IDL.Nat,
    'overallTaskScore' : IDL.Nat,
    'onboardingMaterial' : IDL.Text,
    'subtaskRequiredCount' : IDL.Nat,
    'serviceReference' : IDL.Text,
    'schedule' : Schedule,
  });
  const UserStatus = IDL.Variant({
    'active' : IDL.Null,
    'pending' : IDL.Null,
    'suspended' : IDL.Null,
    'blacklisted' : IDL.Null,
  });
  const PartnerRegistrationData = IDL.Record({
    'name' : IDL.Text,
    'whatsapp' : IDL.Text,
    'email' : IDL.Text,
    'domisili' : IDL.Text,
    'skills' : IDL.Text,
  });
  const ClientRegistrationData = IDL.Record({
    'name' : IDL.Text,
    'whatsapp' : IDL.Text,
    'email' : IDL.Text,
    'company' : IDL.Text,
  });
  const InternalRegistrationData = IDL.Record({
    'name' : IDL.Text,
    'whatsapp' : IDL.Text,
    'email' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'id' : IDL.Text,
    'status' : UserStatus,
    'partnerData' : IDL.Opt(PartnerRegistrationData),
    'clientData' : IDL.Opt(ClientRegistrationData),
    'internalData' : IDL.Opt(InternalRegistrationData),
    'role' : IDL.Text,
    'principalId' : IDL.Text,
  });
  const FinancialSummary = IDL.Record({
    'completedPayouts' : IDL.Nat,
    'totalPayoutAmount' : IDL.Nat,
    'completedTransactions' : IDL.Nat,
    'totalTransactionAmount' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'claimSuperadmin' : IDL.Func([], [IDL.Text], []),
    'createFinancialPartnerData' : IDL.Func([FinancialPartnerData], [], []),
    'createService' : IDL.Func([Service], [], []),
    'createTask' : IDL.Func([Task], [], []),
    'getAllFinancialPartnerData' : IDL.Func(
        [],
        [IDL.Vec(FinancialPartnerData)],
        ['query'],
      ),
    'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDefaultPartnerProfile' : IDL.Func([], [UserProfile], ['query']),
    'getFinancialPartnerDataById' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(FinancialPartnerData)],
        ['query'],
      ),
    'getFinancialSummary' : IDL.Func([], [FinancialSummary], ['query']),
    'getMyWallet' : IDL.Func([], [FinancialPartnerData], ['query']),
    'getServiceById' : IDL.Func([IDL.Text], [IDL.Opt(Service)], ['query']),
    'getTaskById' : IDL.Func([IDL.Text], [IDL.Opt(Task)], ['query']),
    'getUserProfile' : IDL.Func([IDL.Text], [IDL.Opt(UserProfile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isValidRoleName' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'registerClient' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'registerInternalUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'registerPartner' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };